name: Evolution X Build Test for Pixel 5 (redfin)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 python-is-python3
          # repoコマンドのインストール
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Sync Evolution X Source
        run: |
          mkdir ~/evo
          cd ~/evo
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          repo init -u https://github.com/Evolution-X/manifest -b bq2 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Sync Device Specific Trees
        run: |
          cd ~/evo
          git clone https://github.com/Evolution-X-Devices/device_google_redfin -b bq2 device/google/redfin
          git clone https://github.com/Evolution-X-Devices/vendor_google_redfin -b bq2 vendor/google/redfin
          git clone https://github.com/Evolution-X-Devices/kernel_google_redbull -b bq2 kernel/google/redbull

      - name: Check Sync Result
        run: |
          echo "Sync completed successfully!"
          ls -R ~/evo/device/google/redfin
